steps:
  - label: ':face_with_monocle: Deduplicate'
    key: deduplicate
    commands:
      - ./ci/deduplicate.sh
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'

  - label: ':white_check_mark: Lint'
    key: lint
    commands:
      - ./ci/lint.sh
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'

  - label: ':mag: Check'
    key: check
    commands:
      - ./ci/check.sh
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'

  - label: ':hammer_and_pick: Build All Packages'
    key: build
    agents:
      queue: build # build queues run on bigger instances.
    commands:
      - ./ci/build.sh
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'
    artifact_paths:
      - '**/dist/**'

  - label: ':memo: Test'
    key: test
    commands:
      - ./ci/test.sh
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'

  #   _______   ___________    ____
  #  |       \ |   ____\   \  /   /
  #  |  .--.  ||  |__   \   \/   /
  #  |  |  |  ||   __|   \      /
  #  |  '--'  ||  |____   \    /
  #  |_______/ |_______|   \__/
  #

  # ----------------------------------
  # Dev Building and Pushing Website
  # ----------------------------------
  - label: ':hammer_and_pick: Build LUI Website'
    key: build-website
    branches: '!master'
    agents:
      queue: build # build queues run on bigger instances.
    allow_dependency_failure: false
    depends_on:
      - step: test
    commands:
      - ./ci/build-lui-website.sh development
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'
    artifact_paths:
      - 'website/dist/**'

  - label: ':rocket: Deploy LUI Website'
    key: deploy-website
    branches: '!master'
    allow_dependency_failure: false
    depends_on:
      - step: build-website
    commands:
      - ./ci/deploy-lui-website.sh development
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'

  #  .______   .______        ______    _______
  #  |   _  \  |   _  \      /  __  \  |       \
  #  |  |_)  | |  |_)  |    |  |  |  | |  .--.  |
  #  |   ___/  |      /     |  |  |  | |  |  |  |
  #  |  |      |  |\  \----.|  `--'  | |  '--'  |
  #  | _|      | _| `._____| \______/  |_______/
  #

  # ----------------------------------
  # Prod Building and Pushing Packages
  # ----------------------------------
  - label: ':hammer_and_pick: Build LUI Website'
    key: build-website-prod
    branches: 'master'
    agents:
      queue: build # build queues run on bigger instances.
    allow_dependency_failure: false
    depends_on:
      - step: test
    commands:
      - ./ci/build-lui-website.sh production
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'
    artifact_paths:
      - 'website/dist/**'

  - label: ':rocket: Deploy LUI Website'
    key: deploy-website-prod
    branches: 'master'
    allow_dependency_failure: false
    depends_on:
      - step: build-website-prod
    commands:
      - ./ci/deploy-lui-website.sh production
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'

  - label: ':package: Publish'
    key: publish-packages
    branches: 'master'
    agents:
      queue: build # build queues run on bigger instances.
    allow_dependency_failure: false
    depends_on:
      - step: build
    commands:
      - ./ci/publish.sh
    plugins:
      - lendi-au/ssm#0.5.2:
          ssmkey: 'NPM_TOKEN'
