export const AUSTRALIA_STATES = [
  { value: '', label: 'Select ...' },
  { value: 'ACT', label: 'ACT' },
  { value: 'NSW', label: 'NSW' },
  { value: 'NT', label: 'NT' },
  { value: 'QLD', label: 'QLD' },
  { value: 'SA', label: 'SA' },
  { value: 'TAS', label: 'TAS' },
  { value: 'VIC', label: 'VIC' },
  { value: 'WA', label: 'WA' },
];

export const STREET_TYPE = [
  { value: 'Access', label: 'Access' },
  { value: 'Alley', label: 'Alley' },
  { value: 'Alleyway', label: 'Alleyway' },
  { value: 'Amble', label: 'Amble' },
  { value: 'Approach', label: 'Approach' },
  { value: 'Arcade', label: 'Arcade' },
  { value: 'Arterial', label: 'Arterial' },
  { value: 'Artery', label: 'Artery' },
  { value: 'Avenue', label: 'Avenue' },
  { value: 'Banan', label: 'Banan' },
  { value: 'Bend', label: 'Bend' },
  { value: 'Boardwalk', label: 'Boardwalk' },
  { value: 'Boulevard', label: 'Boulevard' },
  { value: 'Brace', label: 'Brace' },
  { value: 'Brae', label: 'Brae' },
  { value: 'Break', label: 'Break' },
  { value: 'Brow', label: 'Brow' },
  { value: 'Bypass', label: 'Bypass' },
  { value: 'Byway', label: 'Byway' },
  { value: 'Causeway', label: 'Causeway' },
  { value: 'Centre', label: 'Centre' },
  { value: 'Chase', label: 'Chase' },
  { value: 'Circle', label: 'Circle' },
  { value: 'Circuit', label: 'Circuit' },
  { value: 'Circus', label: 'Circus' },
  { value: 'Close', label: 'Close' },
  { value: 'Concourse', label: 'Concourse' },
  { value: 'Copse', label: 'Copse' },
  { value: 'Corner', label: 'Corner' },
  { value: 'Court', label: 'Court' },
  { value: 'Courtyard', label: 'Courtyard' },
  { value: 'Cove', label: 'Cove' },
  { value: 'Crescent', label: 'Crescent' },
  { value: 'Crest', label: 'Crest' },
  { value: 'Cross', label: 'Cross' },
  { value: 'Cul-de-sac', label: 'Cul-de-sac' },
  { value: 'Cutting', label: 'Cutting' },
  { value: 'Dale', label: 'Dale' },
  { value: 'Dip', label: 'Dip' },
  { value: 'Drive', label: 'Drive' },
  { value: 'Driveway', label: 'Driveway' },
  { value: 'Edge', label: 'Edge' },
  { value: 'Elbow', label: 'Elbow' },
  { value: 'End', label: 'End' },
  { value: 'Entrance', label: 'Entrance' },
  { value: 'Esplanade', label: 'Esplanade' },
  { value: 'Expressway', label: 'Expressway' },
  { value: 'Fairway', label: 'Fairway' },
  { value: 'Follow', label: 'Follow' },
  { value: 'Footway', label: 'Footway' },
  { value: 'Formation', label: 'Formation' },
  { value: 'Freeway', label: 'Freeway' },
  { value: 'Frontage', label: 'Frontage' },
  { value: 'Gap', label: 'Gap' },
  { value: 'Gardens', label: 'Gardens' },
  { value: 'Gate', label: 'Gate' },
  { value: 'Glade', label: 'Glade' },
  { value: 'Glen', label: 'Glen' },
  { value: 'Grange', label: 'Grange' },
  { value: 'Green', label: 'Green' },
  { value: 'Grove', label: 'Grove' },
  { value: 'Heights', label: 'Heights' },
  { value: 'Highroad', label: 'Highroad' },
  { value: 'Highway', label: 'Highway' },
  { value: 'Hill', label: 'Hill' },
  { value: 'Interchange', label: 'Interchange' },
  { value: 'Junction', label: 'Junction' },
  { value: 'Key', label: 'Key' },
  { value: 'Lane', label: 'Lane' },
  { value: 'Laneway', label: 'Laneway' },
  { value: 'Line', label: 'Line' },
  { value: 'Link', label: 'Link' },
  { value: 'Lookout', label: 'Lookout' },
  { value: 'Loop', label: 'Loop' },
  { value: 'Mall', label: 'Mall' },
  { value: 'Meander', label: 'Meander' },
  { value: 'Meaning', label: 'Meaning' },
  { value: 'Mews', label: 'Mews' },
  { value: 'Motorway', label: 'Motorway' },
  { value: 'Nook', label: 'Nook' },
  { value: 'Outlook', label: 'Outlook' },
  { value: 'Parade', label: 'Parade' },
  { value: 'Parkway', label: 'Parkway' },
  { value: 'Pass', label: 'Pass' },
  { value: 'Passage', label: 'Passage' },
  { value: 'Path', label: 'Path' },
  { value: 'Pathway', label: 'Pathway' },
  { value: 'Piazza', label: 'Piazza' },
  { value: 'Plaza', label: 'Plaza' },
  { value: 'Pocket', label: 'Pocket' },
  { value: 'Point', label: 'Point' },
  { value: 'Port', label: 'Port' },
  { value: 'Promenade', label: 'Promenade' },
  { value: 'Quadrant', label: 'Quadrant' },
  { value: 'Quays', label: 'Quays' },
  { value: 'Ramble', label: 'Ramble' },
  { value: 'Rest', label: 'Rest' },
  { value: 'Retreat', label: 'Retreat' },
  { value: 'Ridge', label: 'Ridge' },
  { value: 'Rise', label: 'Rise' },
  { value: 'Road', label: 'Road' },
  { value: 'Rotary', label: 'Rotary' },
  { value: 'Route', label: 'Route' },
  { value: 'Row', label: 'Row' },
  { value: 'Rue', label: 'Rue' },
  { value: 'Serviceway', label: 'Serviceway' },
  { value: 'Shunt', label: 'Shunt' },
  { value: 'Spur', label: 'Spur' },
  { value: 'Square', label: 'Square' },
  { value: 'Street', label: 'Street' },
  { value: 'Subway', label: 'Subway' },
  { value: 'Tarn', label: 'Tarn' },
  { value: 'Terrace', label: 'Terrace' },
  { value: 'Thoroughfare', label: 'Thoroughfare' },
  { value: 'Tollway', label: 'Tollway' },
  { value: 'Top', label: 'Top' },
  { value: 'Tor', label: 'Tor' },
  { value: 'Track', label: 'Track' },
  { value: 'Trail', label: 'Trail' },
  { value: 'Turn', label: 'Turn' },
  { value: 'Underpass', label: 'Underpass' },
  { value: 'Vale', label: 'Vale' },
  { value: 'Viaduct', label: 'Viaduct' },
  { value: 'View', label: 'View' },
  { value: 'Vista', label: 'Vista' },
  { value: 'Walk', label: 'Walk' },
  { value: 'Walkway', label: 'Walkway' },
  { value: 'Wharf', label: 'Wharf' },
  { value: 'Wynd', label: 'Wynd' },
];

export const COUNTRY = [
  { label: 'Afghanistan', value: 'Afghanistan' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'American Samoa', value: 'American Samoa' },
  { label: 'Andorra', value: 'Andorra' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Anguilla', value: 'Anguilla' },
  { label: 'Antarctica', value: 'Antarctica' },
  { label: 'Antigua And Barbuda', value: 'Antigua And Barbuda' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Armenia', value: 'Armenia' },
  { label: 'Aruba', value: 'Aruba' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Azerbaijan', value: 'Azerbaijan' },
  { label: 'Bahamas', value: 'Bahamas' },
  { label: 'Bahrain', value: 'Bahrain' },
  { label: 'Bangladesh', value: 'Bangladesh' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Belarus', value: 'Belarus' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Belize', value: 'Belize' },
  { label: 'Benin', value: 'Benin' },
  { label: 'Bermuda', value: 'Bermuda' },
  { label: 'Bhutan', value: 'Bhutan' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Bosnia And Herzegovina', value: 'Bosnia And Herzegovina' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'Bouvet Island', value: 'Bouvet Island' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'British Indian Ocean Territory', value: 'British Indian Ocean Territory' },
  { label: 'Brunei Darussalam', value: 'Brunei Darussalam' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Burundi', value: 'Burundi' },
  { label: 'Cambodia', value: 'Cambodia' },
  { label: 'Cameroon', value: 'Cameroon' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Cape Verde', value: 'Cape Verde' },
  { label: 'Cayman Islands', value: 'Cayman Islands' },
  { label: 'Central African Republic', value: 'Central African Republic' },
  { label: 'Chad', value: 'Chad' },
  { label: 'Chile', value: 'Chile' },
  { label: 'China', value: 'China' },
  { label: 'Christmas Island', value: 'Christmas Island' },
  { label: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Comoros', value: 'Comoros' },
  { label: "Democratic People's Republic of Korea", value: "Democratic People's Republic of Korea" },
  { label: 'Democratic Republic Of The Congo', value: 'Democratic Republic Of The Congo' },
  { label: 'Cook Islands', value: 'Cook Islands' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: "Cote D'ivoire", value: "Cote D'ivoire" },
  { label: 'Croatia', value: 'Croatia' },
  { label: 'Cuba', value: 'Cuba' },
  { label: 'Cyprus', value: 'Cyprus' },
  { label: 'Czech Republic', value: 'Czech Republic' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Djibouti', value: 'Djibouti' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'Dominican Republic', value: 'Dominican Republic' },
  { label: 'East Timor', value: 'East Timor' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { label: 'Eritrea', value: 'Eritrea' },
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Falkland Islands', value: 'Falkland Islands' },
  { label: 'Faroe Islands', value: 'Faroe Islands' },
  { label: 'Fiji', value: 'Fiji' },
  { label: 'Finland', value: 'Finland' },
  { label: 'France', value: 'France' },
  { label: 'French Guiana', value: 'French Guiana' },
  { label: 'French Polynesia', value: 'French Polynesia' },
  { label: 'French Southern Territories', value: 'French Southern Territories' },
  { label: 'Gabon', value: 'Gabon' },
  { label: 'Gambia', value: 'Gambia' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'Gibraltar', value: 'Gibraltar' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Greenland', value: 'Greenland' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Guadeloupe', value: 'Guadeloupe' },
  { label: 'Guam', value: 'Guam' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Guinea', value: 'Guinea' },
  { label: 'Guinea-bissau', value: 'Guinea-bissau' },
  { label: 'Guyana', value: 'Guyana' },
  { label: 'Haiti', value: 'Haiti' },
  { label: 'Heard Island And Mcdonald Islands', value: 'Heard Island And Mcdonald Islands' },
  { label: 'Holy See (Vatican City State)', value: 'Holy See (Vatican City State)' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'Hong Kong', value: 'Hong Kong' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Iceland', value: 'Iceland' },
  { label: 'India', value: 'India' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Iran', value: 'Iran' },
  { label: 'Iraq', value: 'Iraq' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Jordan', value: 'Jordan' },
  { label: 'Kazakstan', value: 'Kazakstan' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'Kiribati', value: 'Kiribati' },
  { label: 'Kosovo', value: 'Kosovo' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  { label: 'Laos', value: 'Laos' },
  { label: 'Latvia', value: 'Latvia' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Lesotho', value: 'Lesotho' },
  { label: 'Liberia', value: 'Liberia' },
  { label: 'Libyan Arab Jamahiriya', value: 'Libyan Arab Jamahiriya' },
  { label: 'Liechtenstein', value: 'Liechtenstein' },
  { label: 'Lithuania', value: 'Lithuania' },
  { label: 'Luxembourg', value: 'Luxembourg' },
  { label: 'Macau', value: 'Macau' },
  { label: 'Macedonia', value: 'Macedonia' },
  { label: 'Madagascar', value: 'Madagascar' },
  { label: 'Malawi', value: 'Malawi' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'Maldives', value: 'Maldives' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Marshall Islands', value: 'Marshall Islands' },
  { label: 'Martinique', value: 'Martinique' },
  { label: 'Mauritania', value: 'Mauritania' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Mayotte', value: 'Mayotte' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Federated States Of Micronesia', value: 'Federated States Of Micronesia' },
  { label: 'Republic Of Moldova', value: 'Republic Of Moldova' },
  { label: 'Monaco', value: 'Monaco' },
  { label: 'Mongolia', value: 'Mongolia' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Montenegro', value: 'Montenegro' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Myanmar', value: 'Myanmar' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Nauru', value: 'Nauru' },
  { label: 'Nepal', value: 'Nepal' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Netherlands Antilles', value: 'Netherlands Antilles' },
  { label: 'New Caledonia', value: 'New Caledonia' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Niue', value: 'Niue' },
  { label: 'Norfolk Island', value: 'Norfolk Island' },
  { label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Oman', value: 'Oman' },
  { label: 'Pakistan', value: 'Pakistan' },
  { label: 'Palau', value: 'Palau' },
  { label: 'Palestinian Territory', value: 'Palestinian Territory' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Pitcairn', value: 'Pitcairn' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Puerto Rico', value: 'Puerto Rico' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Russian Federation', value: 'Russian Federation' },
  { label: 'Rwanda', value: 'Rwanda' },
  { label: 'Saint Helena', value: 'Saint Helena' },
  { label: 'Saint Kitts And Nevis', value: 'Saint Kitts And Nevis' },
  { label: 'Saint Lucia', value: 'Saint Lucia' },
  { label: 'Saint Pierre And Miquelon', value: 'Saint Pierre And Miquelon' },
  { label: 'Saint Vincent And The Grenadines', value: 'Saint Vincent And The Grenadines' },
  { label: 'Samoa', value: 'Samoa' },
  { label: 'San Marino', value: 'San Marino' },
  { label: 'Sao Tome And Principe', value: 'Sao Tome And Principe' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Serbia', value: 'Serbia' },
  { label: 'Seychelles', value: 'Seychelles' },
  { label: 'Sierra Leone', value: 'Sierra Leone' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Slovakia', value: 'Slovakia' },
  { label: 'Slovenia', value: 'Slovenia' },
  { label: 'Solomon Islands', value: 'Solomon Islands' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'South Georgia And The South Sandwich Islands', value: 'South Georgia And The South Sandwich Islands' },
  { label: 'The Republic of South Korea', value: 'The Republic of South Korea' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Sri Lanka', value: 'Sri Lanka' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Suriname', value: 'Suriname' },
  { label: 'Svalbard And Jan Mayen', value: 'Svalbard And Jan Mayen' },
  { label: 'Swaziland', value: 'Swaziland' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
  { label: 'Taiwan', value: 'Taiwan' },
  { label: 'Tajikistan', value: 'Tajikistan' },
  { label: 'Tanzania', value: 'Tanzania' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'Togo', value: 'Togo' },
  { label: 'Tokelau', value: 'Tokelau' },
  { label: 'Tonga', value: 'Tonga' },
  { label: 'Trinidad And Tobago', value: 'Trinidad And Tobago' },
  { label: 'Tunisia', value: 'Tunisia' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Turkmenistan', value: 'Turkmenistan' },
  { label: 'Turks And Caicos Islands', value: 'Turks And Caicos Islands' },
  { label: 'Tuvalu', value: 'Tuvalu' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Ukraine', value: 'Ukraine' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States of America', value: 'United States of America' },
  { label: 'United States Minor Outlying Islands', value: 'United States Minor Outlying Islands' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Uzbekistan', value: 'Uzbekistan' },
  { label: 'Vanuatu', value: 'Vanuatu' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'British Virgin Islands', value: 'British Virgin Islands' },
  { label: 'US Virgin Islands', value: 'US Virgin Islands' },
  { label: 'Wallis And Futuna', value: 'Wallis And Futuna' },
  { label: 'Western Sahara', value: 'Western Sahara' },
  { label: 'Yemen', value: 'Yemen' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
];
